version: '3'
services:
  nginx:
    image: nginx:stable-bullseye
    ports:
      - "80:80"
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - carlot
  php:
    image: php:fpm
    volumes:
      - ./backend/src:/var/www/html
    links:
      - db
    networks:
      - carlot
  db:
    image: mariadb:lts
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: carlot_root
      MYSQL_DATABASE: carlot
      MYSQL_USER: carlot
      MYSQL_PASSWORD: carlot
    networks:
      - carlot

networks:
  carlot:
    driver: bridge
    external: true